env:
  es6: true
  node: true
extends:
  - google
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:'@typescript-eslint/no-floating-promises'
  - plugin:'@typescript-eslint/no-unsafe-member-access'
  - plugin:'@typescript-eslint/no-unsafe-call'
  - plugin:'@typescript-eslint/no-unsafe-return'
  - plugin:'@typescript-eslint/no-unsafe-assignment'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: tsconfig.json
  sconfigRootDir: "./src"
plugins:
  - '@typescript-eslint'
rules:
  require-jsdoc: 0
